// <auto-generated />
using System;
using BrookBallersWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrookBallersWebApp.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20200324012033_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrookBallersWebApp.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Apps")
                        .HasColumnType("int");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<string>("Foot")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Red")
                        .HasColumnType("int");

                    b.Property<int>("TGA")
                        .HasColumnType("int");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.Property<int>("Yel")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            Age = 24,
                            Apps = 7,
                            Assists = 6,
                            Foot = "R",
                            Goals = 4,
                            PlayerName = "Hassan A",
                            Pos = "M",
                            Red = 0,
                            TGA = 10,
                            TeamID = 1,
                            Yel = 0
                        },
                        new
                        {
                            PlayerID = 2,
                            Age = 25,
                            Apps = 10,
                            Assists = 2,
                            Foot = "R",
                            Goals = 3,
                            PlayerName = "Mohammed H",
                            Pos = "F",
                            Red = 0,
                            TGA = 5,
                            TeamID = 6,
                            Yel = 4
                        });
                });

            modelBuilder.Entity("BrookBallersWebApp.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("D")
                        .HasColumnType("int");

                    b.Property<int>("GA")
                        .HasColumnType("int");

                    b.Property<int>("GD")
                        .HasColumnType("int");

                    b.Property<int>("GF")
                        .HasColumnType("int");

                    b.Property<int>("L")
                        .HasColumnType("int");

                    b.Property<int>("MP")
                        .HasColumnType("int");

                    b.Property<int>("PTS")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.HasKey("TeamID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            D = 1,
                            GA = 52,
                            GD = 38,
                            GF = 16,
                            L = 0,
                            MP = 10,
                            PTS = 28,
                            TeamName = "Tekk Republic",
                            W = 9
                        },
                        new
                        {
                            TeamID = 6,
                            D = 1,
                            GA = 67,
                            GD = -45,
                            GF = 22,
                            L = 8,
                            MP = 10,
                            PTS = 4,
                            TeamName = "L.Hermanos",
                            W = 1
                        },
                        new
                        {
                            TeamID = 2,
                            D = 0,
                            GA = 33,
                            GD = 19,
                            GF = 52,
                            L = 3,
                            MP = 10,
                            PTS = 21,
                            TeamName = "AR FC",
                            W = 7
                        },
                        new
                        {
                            TeamID = 5,
                            D = 0,
                            GA = 64,
                            GD = -32,
                            GF = 32,
                            L = 7,
                            MP = 10,
                            PTS = 9,
                            TeamName = "Eagles United",
                            W = 3
                        },
                        new
                        {
                            TeamID = 3,
                            D = 1,
                            GA = 39,
                            GD = 5,
                            GF = 44,
                            L = 5,
                            MP = 10,
                            PTS = 13,
                            TeamName = "Hurli FC",
                            W = 4
                        },
                        new
                        {
                            TeamID = 4,
                            D = 1,
                            GA = 30,
                            GD = 15,
                            GF = 45,
                            L = 5,
                            MP = 10,
                            PTS = 13,
                            TeamName = "Akdem FC",
                            W = 4
                        });
                });

            modelBuilder.Entity("BrookBallersWebApp.Models.Player", b =>
                {
                    b.HasOne("BrookBallersWebApp.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID");
                });
#pragma warning restore 612, 618
        }
    }
}
